### ISSUE TITLE
History Tracking

### ISSUE THREAD

**Issue by feildmaster** [WhenApp/WhenApp-Android#3]
> when you "Click" to expand the task, it shows a history of when it was reset.
Header of... History (ResetCount)

>good idea
can be stored internally just as an array of longs

Optional: "Notes" that can be attached to specific resets.

- [ ] History in "Task" view
- [ ] Attach notes
- [ ] Allow deletion of history entries
- [ ] Ability to disable history per task

Blocked by #20
